use sea_orm::DatabaseConnection;

pub mod equipment;
pub mod equipment_status_log;
pub mod equipment_mqtt_config;
pub mod equipment_maintenance_plans;
pub mod equipment_maintenance_tasks;
pub mod equipment_fault_reports;
pub mod equipment_repair_orders;
pub mod equipment_inspections;
pub mod equipment_kpi;
pub mod material_categories;
pub mod materials;
pub mod suppliers;
pub mod customers;
pub mod workshops;
pub mod warehouses;
pub mod locations;
pub mod boms;
pub mod process_routes;
pub mod production_plans;
pub mod production_orders;
pub mod work_orders;
pub mod production_reports;
pub mod production_schedules;
pub mod material_requirements;
pub mod picking_orders;
pub mod picking_order_lines;
pub mod return_orders;
pub mod return_order_lines;
pub mod production_receipts;
pub mod inventory;
pub mod inbound_orders;
pub mod inbound_order_details;
pub mod outbound_orders;
pub mod outbound_order_lines;
pub mod transfer_orders;
pub mod transfer_order_lines;
pub mod stock_count_orders;
pub mod stock_count_lines;
pub mod stock_adjustments;
pub mod stock_reservations;
pub mod stock_transactions;
pub mod stock_alert_rules;
pub mod batch_traceability;
pub mod departments;
pub mod users;
pub mod login_logs;
pub mod operation_logs;
pub mod roles;
pub mod permissions;
pub mod user_roles;
pub mod role_permissions;
pub mod quality_inspection_tasks;
pub mod quality_inspection_reports;
pub mod quality_inspection_items;
pub mod nonconforming_products;
pub mod rework_orders;
pub mod customer_complaints;
pub mod supplier_quality_evaluations;
pub mod quality_traceability_records;
pub mod measuring_equipment;
pub mod equipment_calibration_records;
pub mod quality_costs;
pub mod quality_kpi;

pub use equipment::Entity as Equipment;
pub use equipment_status_log::Entity as EquipmentStatusLog;
pub use equipment_mqtt_config::Entity as EquipmentMqttConfig;
pub use equipment_maintenance_plans::Entity as EquipmentMaintenancePlans;
pub use equipment_maintenance_tasks::Entity as EquipmentMaintenanceTasks;
pub use equipment_fault_reports::Entity as EquipmentFaultReports;
pub use equipment_repair_orders::Entity as EquipmentRepairOrders;
pub use equipment_inspections::Entity as EquipmentInspections;
pub use equipment_kpi::Entity as EquipmentKpi;
pub use material_categories::Entity as MaterialCategories;
pub use materials::Entity as Materials;
pub use suppliers::Entity as Suppliers;
pub use customers::Entity as Customers;
pub use workshops::Entity as Workshops;
pub use warehouses::Entity as Warehouses;
pub use locations::Entity as Locations;
pub use boms::Entity as Boms;
pub use process_routes::Entity as ProcessRoutes;
pub use production_plans::Entity as ProductionPlans;
pub use production_orders::Entity as ProductionOrders;
pub use work_orders::Entity as WorkOrders;
pub use production_reports::Entity as ProductionReports;
pub use production_schedules::Entity as ProductionSchedules;
pub use material_requirements::Entity as MaterialRequirements;
pub use picking_orders::Entity as PickingOrders;
pub use picking_order_lines::Entity as PickingOrderLines;
pub use return_orders::Entity as ReturnOrders;
pub use return_order_lines::Entity as ReturnOrderLines;
pub use production_receipts::Entity as ProductionReceipts;
pub use inventory::Entity as Inventory;
pub use inbound_orders::Entity as InboundOrders;
pub use inbound_order_details::Entity as InboundOrderDetails;
pub use outbound_orders::Entity as OutboundOrders;
pub use outbound_order_lines::Entity as OutboundOrderLines;
pub use transfer_orders::Entity as TransferOrders;
pub use transfer_order_lines::Entity as TransferOrderLines;
pub use stock_count_orders::Entity as StockCountOrders;
pub use stock_count_lines::Entity as StockCountLines;
pub use stock_adjustments::Entity as StockAdjustments;
pub use stock_reservations::Entity as StockReservations;
pub use stock_transactions::Entity as StockTransactions;
pub use stock_alert_rules::Entity as StockAlertRules;
pub use batch_traceability::Entity as BatchTraceability;
pub use departments::Entity as Departments;
pub use users::Entity as Users;
pub use login_logs::Entity as LoginLogs;
pub use operation_logs::Entity as OperationLogs;
pub use roles::Entity as Roles;
pub use permissions::Entity as Permissions;
pub use user_roles::Entity as UserRoles;
pub use role_permissions::Entity as RolePermissions;
pub use quality_inspection_tasks::Entity as QualityInspectionTasks;
pub use quality_inspection_reports::Entity as QualityInspectionReports;
pub use quality_inspection_items::Entity as QualityInspectionItems;
pub use nonconforming_products::Entity as NonconformingProducts;
pub use rework_orders::Entity as ReworkOrders;
pub use customer_complaints::Entity as CustomerComplaints;
pub use supplier_quality_evaluations::Entity as SupplierQualityEvaluations;
pub use quality_traceability_records::Entity as QualityTraceabilityRecords;
pub use measuring_equipment::Entity as MeasuringEquipment;
pub use equipment_calibration_records::Entity as EquipmentCalibrationRecords;
pub use quality_costs::Entity as QualityCosts;
pub use quality_kpi::Entity as QualityKpi;

// Helper type alias so DAOs can accept a generic connection
pub type ConnRef<'a> = &'a DatabaseConnection;


