#[derive(Clone, Debug, PartialEq)]
pub struct Model {
    
    pub id: i64,
    pub order_no: String,
    pub plan_id: Option<i64>,
    pub source_type: i8,
    pub source_order_no: Option<String>,
    pub material_id: i64,
    pub bom_id: Option<i64>,
    pub routing_id: Option<i64>,
    pub plan_quantity: Decimal,
    pub actual_quantity: Decimal,
    pub qualified_quantity: Decimal,
    pub unqualified_quantity: Decimal,
    pub scrap_quantity: Decimal,
    pub unit: String,
    pub priority: i8,
    pub plan_start_date: Date,
    pub plan_end_date: Date,
    pub actual_start_date: Option<chrono::NaiveDate>,
    pub actual_end_date: Option<chrono::NaiveDate>,
    pub workshop_id: Option<i64>,
    pub production_line: Option<String>,
    pub batch_no: Option<String>,
    pub customer_id: Option<i64>,
    pub order_status: i8,
    pub is_locked: i8,
    pub is_urgent: i8,
    pub standard_hours: Decimal,
    pub actual_hours: Decimal,
    pub leader_id: Option<i64>,
    pub planner_id: Option<i64>,
    pub remark: Option<String>,
    pub created_by: Option<i64>,
    pub created_time: chrono::DateTime<chrono::Utc>,
    pub updated_by: Option<i64>,
    pub updated_time: chrono::DateTime<chrono::Utc>,
    pub is_deleted: i8,
}

